version: '3.8'

services:
  server:
    build:
      context: ./app
    ports:
      - 80:5000
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    entrypoint: /app/entrypoint.sh
    restart: always

  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=yournal
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/prod_password.txt
